[ids]
*

[main]
leftalt = overload(mac_style, leftalt)

[mac_style:C]
# Utilisation des touches "Copy/Paste" dédiées de Linux
# Cela évite le conflit avec Ctrl+C (SIGINT) dans le terminal
c = copy
v = paste
x = cut
# Pour le reste, on peut rester sur du Ctrl classique
a = C-a
s = C-s
f = C-f
z = C-z
t = C-t
w = C-w
q = A-f4
tab = A-tab

# Navigation Mac-style (Alt + flèches)
left = C-left
right = C-right
backspace = C-backspace

# Custom key
wlan = f24
