[ids]
*

[main]
leftalt = overload(mac_style, leftalt)

[mac_style:C]
c = C-c
v = C-v
x = C-x
z = C-z
a = C-a
s = C-s
f = C-f
t = C-t
w = C-w
n = C-n
r = C-r
l = C-l
enter = C-enter
tab = A-tab
left = C-left
right = C-right
